### ISSUE TITLE
Work Contract

### ISSUE THREAD

**Issue by dorisyycai** [UBC-MDS/quanteda#4] opened 2024-01-11 00:49 UTC
https://docs.google.com/document/d/1wLdZBj2-cqEvSIfLAPJUS5Q1Vy2s5jAEilK6Wso8PQc/edit

**Comment by dorisyycai** [comment] 2024-01-11 01:25
This was done and the contract is stored here:
https://docs.google.com/document/d/1wLdZBj2-cqEvSIfLAPJUS5Q1Vy2s5jAEilK6Wso8PQc/edit

**Comment by JohnShiuMK** [comment] 2024-01-11 08:26
Thanks @dorisyycai

**Comment by JohnShiuMK** [comment] 2024-01-11 08:26
Duplicate of #2

**Comment by meretelutz** [comment] 2024-01-12 20:07
Closing this issue as we have finished the contract

**Closed by meretelutz** 2024-01-12 20:07 UTC
Labels: documentation
